version: 1
services:
  - type: web
    name: maintenance-system
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend  # Set this if package.json is in the backend folder
